"""empty message

Revision ID: 3ad7cf158c06
Revises: 01f28a1b727b
Create Date: 2020-09-20 20:19:53.713523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad7cf158c06'
down_revision = '01f28a1b727b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_member_userEmail'), ['userEmail'])
        batch_op.create_unique_constraint(batch_op.f('uq_member_userId'), ['userId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_member_userId'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_member_userEmail'), type_='unique')

    # ### end Alembic commands ###
