"""empty message

Revision ID: bf63b3144285
Revises: b1936d033ef5
Create Date: 2020-09-20 23:21:51.374139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf63b3144285'
down_revision = 'b1936d033ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
